[package]
name = "hotchkiss-io"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
askama = "0.12.1"
axum = "0.7.7"
axum-server = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.41.1", features = ["full"] }
tower = "0.5.1"
tower-http = { version = "0.6.1", features = ["fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
