name: Test and Coverage
on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: macos-latest
    env:
      RUSTFLAGS: "-Cinstrument-coverage"
    steps:
      - name: Install Tools
        run: |
          rustup target add aarch64-apple-darwin && \
          cargo install grcov && \
          rustup component add llvm-tools
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build the code
        run: cargo build
      - name: Test The code
        env:
          LLVM_PROFILE_FILE: "hotchkiss-io-%p-%m.profraw"
        run: cargo test
      - name: Generate Coverage Report
        run: |
          genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend ./target/debug/lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
